name: Deploy to Azure Web Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: rush-policy-chat    # Set this to your Azure Web App name
  NODE_VERSION: '20.x'                   # Node.js version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Next.js application
      run: npm run build
      env:
        NODE_ENV: production

    - name: List build output (for debugging)
      run: |
        echo "Build directory contents:"
        ls -la .next/
        if [ -d ".next/standalone" ]; then
          echo "Standalone build detected:"
          ls -la .next/standalone/
        fi

    - name: Create deployment package
      run: |
        # Create a clean deployment directory
        mkdir -p deployment

        # Copy standalone build if it exists
        if [ -d ".next/standalone" ]; then
          echo "Copying standalone build..."
          cp -r .next/standalone/* deployment/

          # Copy static assets
          if [ -d ".next/static" ]; then
            mkdir -p deployment/.next/static
            cp -r .next/static/* deployment/.next/static/
          fi

          # Copy public assets
          if [ -d "public" ]; then
            mkdir -p deployment/public
            cp -r public/* deployment/public/
          fi
        else
          echo "Copying full Next.js build..."
          cp -r .next deployment/
          cp -r node_modules deployment/
          cp -r public deployment/
          cp package*.json deployment/
        fi

        # Copy Azure configuration files
        cp startup.sh deployment/ || echo "startup.sh not found"
        cp web.config deployment/ || echo "web.config not found"
        cp .deployment deployment/ || echo ".deployment not found"

        # Make startup script executable
        chmod +x deployment/startup.sh || true

        echo "Deployment package created successfully"
        ls -la deployment/

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: rush-policy-chat-app
        path: deployment/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: rush-policy-chat-app
        path: .

    - name: List deployment files (for debugging)
      run: |
        echo "Files to be deployed:"
        ls -la

    - name: Deploy to Azure Web Apps
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

    - name: Deployment summary
      run: |
        echo "==================================="
        echo "Deployment completed successfully!"
        echo "==================================="
        echo "App Name: ${{ env.AZURE_WEBAPP_NAME }}"
        echo "App URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
        echo "Node Version: ${{ env.NODE_VERSION }}"
        echo "==================================="
